version: "3"

includes:
  common: ./build/Taskfile.yml
  darwin: ./build/darwin/Taskfile.yml
  linux: ./build/linux/Taskfile.yml
  windows: ./build/windows/Taskfile.yml

vars:
  APP_NAME: "ap"
  APP_TITLE: "Afterpiece"
  BIN_DIR: "dist"
  VERSION: '{{.VERSION | default "dev"}}'
  GO_RUNTIME: "ap-go"
  GO_RUNTIME_VERSION: '{{.GO_RUNTIME_VERSION | default "ap-go1.23.0"}}'
  CLI_PACKAGE: "./cli/cmd/afterpiece"
  GIT_REMOTE_PACKAGE: "./cli/cmd/git-remote-encore"
  TSBUNDLER_PACKAGE: "./cli/cmd/tsbundler-encore"

tasks:
  default:
    summary: Shows available tasks
    cmds:
      - task --list

  setup:
    summary: Sets up development environment
    cmds:
      - task: common:setup

  build:
    summary: Builds CLI for current platform
    cmds:
      - task: "{{OS}}:build"

  build:cli:
    summary: Builds only the main CLI for current platform
    cmds:
      - task: "{{OS}}:build:cli"

  test:
    summary: Runs all tests
    cmd: go test -parallel 128 -p 16 -short ./...

  clean:
    summary: Cleans build artifacts
    cmds:
      - rm -rf {{.BIN_DIR}}
      - rm -rf {{.GO_RUNTIME}}
      - rm -f *.tar.gz *.zip

  clean:all:
    summary: Cleans all build artifacts and caches
    deps:
      - task: clean
    cmds:
      - go clean -cache

  version:
    summary: Shows current version
    cmds:
      - 'echo "{{.APP_TITLE}} version: {{.VERSION}}"'
      - 'echo "{{.GO_RUNTIME}} version: {{.GO_RUNTIME_VERSION}}"'

  deps:
    summary: Downloads all dependencies
    cmds:
      - task: common:setup

  dev:
    summary: Runs in development mode
    deps:
      - task: build:cli
    cmds:
      - ./{{.BIN_DIR}}/{{.APP_NAME}} dev

  run:
    summary: Runs built binary
    deps:
      - task: build:cli
    cmds:
      - ./{{.BIN_DIR}}/{{.APP_NAME}} {{.CLI_ARGS}}

  lint:
    summary: Runs linters
    cmds:
      - task: common:lint:go

  fmt:
    summary: Formats code
    cmds:
      - task: common:fmt:go