version: "3"

includes:
  common: ./build/Taskfile.yml
  darwin: ./build/darwin/Taskfile.yml
  linux: ./build/linux/Taskfile.yml
  windows: ./build/windows/Taskfile.yml

vars:
  APP_NAME: "ap"
  BIN_DIR: "dist"
  VERSION: '{{.VERSION | default "dev"}}'
  ENCORE_GO_VERSION: '{{.ENCORE_GO_VERSION | default "ap-go1.23.0"}}'


tasks:
  default:
    summary: Shows available tasks
    cmds:
      - task --list

  setup:
    summary: Sets up development environment
    cmds:
      - task: common:setup

  build:
    summary: Builds Encore CLI for current platform
    cmds:
      - task: "{{OS}}:build"

  build:cli:
    summary: Builds only the main CLI for current platform
    cmds:
      - task: "{{OS}}:build:cli"

  test:
    summary: Runs all tests
    cmd: go test -parallel 128 -p 16 -short ./...

  clean:
    summary: Cleans build artifacts
    cmds:
      - rm -rf {{.BIN_DIR}}
      - rm -rf ap-go
      - rm -f *.tar.gz *.zip

  clean:all:
    summary: Cleans all build artifacts and caches
    deps:
      - task: clean
    cmds:
      - go clean -cache

  version:
    summary: Shows current version
    cmds:
      - 'echo "Afterpiece version: {{.VERSION}}"'
      - 'echo "AP-Go version: {{.ENCORE_GO_VERSION}}"'

  deps:
    summary: Downloads all dependencies
    cmds:
      - task: common:setup

  # Development helpers
  dev:
    summary: Runs Encore in development mode
    deps:
      - task: build:cli
    cmds:
      - ./{{.BIN_DIR}}/encore dev

  run:
    summary: Runs built Encore binary
    deps:
      - task: build:cli
    cmds:
      - ./{{.BIN_DIR}}/encore {{.CLI_ARGS}}

  # Linting and formatting
  lint:
    summary: Runs linters
    cmds:
      - task: common:lint:go

  fmt:
    summary: Formats code
    cmds:
      - task: common:fmt:go
